AWSTemplateFormatVersion: '2010-09-09'
Description: Simple 3-tier web app (ALB + EC2 app tier + RDS MySQL) across two AZs.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetCidrs:
    Type: List<String>
    Default: 10.0.0.0/24,10.0.1.0/24
  PrivateSubnetCidrs:
    Type: List<String>
    Default: 10.0.10.0/24,10.0.11.0/24
  InstanceType:
    Type: String
    Default: t3.micro
  DesiredCapacity:
    Type: Number
    Default: 2
  MinSize:
    Type: Number
    Default: 2
  MaxSize:
    Type: Number
    Default: 4
  DBEngineVersion:
    Type: String
    Default: '8.0.35'
    Description: MySQL engine version
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
  DBMultiAZ:
    Type: String
    AllowedValues: ['true','false']
    Default: 'false'
  DBAllocatedStorage:
    Type: Number
    Default: 20
  AllowedCidrToAlb:
    Type: String
    Default: 0.0.0.0/0
    Description: Who can reach ALB on port 80

Mappings:
  AmiParam:
    AL2023: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

Conditions:
  UseMultiAZ: !Equals [ !Ref DBMultiAZ, 'true' ]

Resources:

  # VPC and Subnets
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags: [{ Key: Name, Value: !Sub '${AWS::StackName}-vpc' }]

  IGW:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Select [0, !Ref PublicSubnetCidrs]
      MapPublicIpOnLaunch: true
      Tags: [{ Key: Name, Value: !Sub '${AWS::StackName}-public-a' }]

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Select [1, !Ref PublicSubnetCidrs]
      MapPublicIpOnLaunch: true
      Tags: [{ Key: Name, Value: !Sub '${AWS::StackName}-public-b' }]

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Select [0, !Ref PrivateSubnetCidrs]
      MapPublicIpOnLaunch: false
      Tags: [{ Key: Name, Value: !Sub '${AWS::StackName}-private-a' }]

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Select [1, !Ref PrivateSubnetCidrs]
      MapPublicIpOnLaunch: false
      Tags: [{ Key: Name, Value: !Sub '${AWS::StackName}-private-b' }]

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  AssocPublicA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  AssocPublicB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable

  # NAT omitted to keep template minimal; app instances will use VPC endpoints for SSM.

  # Security Groups
  AlbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AllowedCidrToAlb

  AppSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: App tier SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref AlbSg

  DbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DB SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppSg

  # ALB
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets: [ !Ref PublicSubnetA, !Ref PublicSubnetB ]
      SecurityGroups: [ !Ref AlbSg ]

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckPath: /

  Listener80:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # IAM for EC2 to read secret and use SSM
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: ReadDbSecret
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: [ 'secretsmanager:GetSecretValue' ]
                Resource: !Ref DbSecret

  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref AppRole ]

  # Secrets Manager for DB credentials
  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Credentials for RDS MySQL
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "appuser"}'
        GenerateStringKey: password
        ExcludeCharacters: '"@/\' # avoid shell issues
        PasswordLength: 24

  # RDS Subnet Group and Instance
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for DB
      SubnetIds: [ !Ref PrivateSubnetA, !Ref PrivateSubnetB ]

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: mysql
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Sub '{{resolve:secretsmanager:${DbSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DbSecret}::password}}'
      VPCSecurityGroups: [ !Ref DbSg ]
      DBSubnetGroupName: !Ref DbSubnetGroup
      MultiAZ: !If [ UseMultiAZ, true, false ]
      StorageEncrypted: true
      BackupRetentionPeriod: 7
      PubliclyAccessible: false

  # Interface endpoints so private instances can reach SSM without public IP
  EndpointSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Interface endpoint SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          SourceSecurityGroupId: !Ref AppSg

  VPCEndpointSSM:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      SubnetIds: [ !Ref PrivateSubnetA, !Ref PrivateSubnetB ]
      SecurityGroupIds: [ !Ref EndpointSg ]

  VPCEndpointEC2Messages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      SubnetIds: [ !Ref PrivateSubnetA, !Ref PrivateSubnetB ]
      SecurityGroupIds: [ !Ref EndpointSg ]

  VPCEndpointSSMMessages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      SubnetIds: [ !Ref PrivateSubnetA, !Ref PrivateSubnetB ]
      SecurityGroupIds: [ !Ref EndpointSg ]

  # Launch Template + ASG for App tier
  AppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile: { Name: !Ref AppInstanceProfile }
        ImageId: !Sub '{{resolve:ssm:${AmiParam.AL2023}}}'
        InstanceType: !Ref InstanceType
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: false
            Groups: [ !Ref AppSg ]
        MetadataOptions:
          HttpTokens: required
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            dnf install -y httpd jq mysql
            systemctl enable httpd
            # Fetch DB secret
            SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id ${DbSecret} --query SecretString --output text --region ${AWS::Region})
            DB_USER=$(echo $SECRET_JSON | jq -r .username)
            DB_PASS=$(echo $SECRET_JSON | jq -r .password)
            DB_HOST='${DBInstance.Endpoint.Address}'
            # Simple health page uses DB connectivity check
            cat >/var/www/html/index.html <<EOF
            <html><body>
            <h1>${AWS::StackName} 3-tier app</h1>
            <p>Status: OK</p>
            <p>DB endpoint: ${DBInstance.Endpoint.Address}</p>
            </body></html>
            EOF
            # Optional: create a simple schema/table if reachable
            mysql -h $DB_HOST -u $DB_USER -p$DB_PASS -e "CREATE DATABASE IF NOT EXISTS appdb; CREATE TABLE IF NOT EXISTS appdb.health (ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP);"
            systemctl start httpd

  AppAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: [ !Ref PrivateSubnetA, !Ref PrivateSubnetB ]
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      TargetGroupARNs: [ !Ref TargetGroup ]
      LaunchTemplate:
        LaunchTemplateId: !Ref AppLaunchTemplate
        Version: !GetAtt AppLaunchTemplate.LatestVersionNumber
      HealthCheckType: ELB
      HealthCheckGracePeriod: 120
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT5M

Outputs:
  LoadBalancerDNS:
    Description: Public DNS of the ALB
    Value: !GetAtt Alb.DNSName
  VpcId:
    Value: !Ref VPC
  AppSecurityGroupId:
    Value: !Ref AppSg
  DbEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
  DbSecretArn:
    Value: !Ref DbSecret
