AWSTemplateFormatVersion: '2010-09-09'
Description: Composer-safe minimal 2-tier (ALB + ASG) to validate template ingestion.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.0.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.1.0/24
  AllowedCidrToAlb:
    Type: String
    Default: 0.0.0.0/0
  InstanceType:
    Type: String
    Default: t3.micro
  AmiId:
    Type: String
    Description: Provide a valid AMI ID for your region (e.g., AL2023).
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: ''
    Description: Optional key pair for debugging (leave empty to skip)

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: { Ref: VpcCidr }
      EnableDnsSupport: true
      EnableDnsHostnames: true

  IGW:
    Type: AWS::EC2::InternetGateway

  VpcIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: { Ref: IGW }
      VpcId: { Ref: VPC }

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: VPC }
      AvailabilityZone: { Fn::Select: [ 0, { Fn::GetAZs: '' } ] }
      CidrBlock: { Ref: PublicSubnet1Cidr }
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: { Ref: VPC }
      AvailabilityZone: { Fn::Select: [ 1, { Fn::GetAZs: '' } ] }
      CidrBlock: { Ref: PublicSubnet2Cidr }
      MapPublicIpOnLaunch: true

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: { Ref: VPC }

  DefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: VpcIgwAttach
    Properties:
      RouteTableId: { Ref: PublicRouteTable }
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: { Ref: IGW }

  AssocPub1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PublicSubnet1 }
      RouteTableId: { Ref: PublicRouteTable }

  AssocPub2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: { Ref: PublicSubnet2 }
      RouteTableId: { Ref: PublicRouteTable }

  AlbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB security group
      VpcId: { Ref: VPC }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: { Ref: AllowedCidrToAlb }

  AppSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: App tier security group
      VpcId: { Ref: VPC }
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: { Ref: AlbSg }

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets: [ { Ref: PublicSubnet1 }, { Ref: PublicSubnet2 } ]
      SecurityGroups: [ { Ref: AlbSg } ]

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: { Ref: VPC }
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckPath: /

  Listener80:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: { Ref: Alb }
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: { Ref: TargetGroup }

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: { Ref: AmiId }
        InstanceType: { Ref: InstanceType }
        KeyName: { Ref: KeyName }
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            Groups: [ { Ref: AppSg } ]
        UserData:
          # Plain static script; no substitutions; single-quoted for YAML safety.
          Fn::Base64: |
            #!/bin/bash -xe
            mkdir -p /opt/app
            echo '<html><body><h1>Composer-safe app</h1><p>Status: OK</p></body></html>' > /opt/app/index.html
            nohup python3 -m http.server 80 --directory /opt/app >/var/log/web.log 2>&1 &

  Asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: [ { Ref: PublicSubnet1 }, { Ref: PublicSubnet2 } ]
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'
      TargetGroupARNs: [ { Ref: TargetGroup } ]
      LaunchTemplate:
        LaunchTemplateId: { Ref: LaunchTemplate }
        Version: { Fn::GetAtt: [ LaunchTemplate, LatestVersionNumber ] }
      HealthCheckType: ELB
      HealthCheckGracePeriod: 120

Outputs:
  LoadBalancerDNS:
    Description: Public DNS of the ALB
    Value: { Fn::GetAtt: [ Alb, DNSName ] }
  VpcId:
    Value: { Ref: VPC }
